//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixSendCdlManually
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdlKitsItems
    {
        public int ID { get; set; }
        public int cdlKitsId { get; set; }
        public bool ItemVerKit { get; set; }
        public int ItemOrKitId { get; set; }
        public string ItemGroupGoods { get; set; }
        public string ItemCode { get; set; }
        public decimal ItemOrKitQuantity { get; set; }
        public string PackageType { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
        public bool IsSent { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
    
        public virtual cdlKits cdlKits { get; set; }
    }
}
